import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class AlbumService {
  constructor() { }

  getAlbums() {
    return Promise.resolve([
      {"artist":"Stearn Jennins","title":"Cassin, D'Amore and Fadel","date": new Date("1/25/2024")},
      {"artist":"Koressa Shears","title":"Stracke-Braun","date": new Date("3/11/2024")},
      {"artist":"Jandy Chadburn","title":"Upton, Corwin and Greenfelder","date": new Date("10/19/2024")},
      {"artist":"Demetris Winny","title":"Blick, Fritsch and Wolf","date": new Date("9/28/2024")},
      {"artist":"Ilse Giamitti","title":"Schmeler and Sons","date": new Date("3/2/2024")},
      {"artist":"Norrie Seeman","title":"Cartwright-Gorczany","date": new Date("5/23/2024")},
      {"artist":"Flor Davidsen","title":"Flatley-Streich","date": new Date("9/14/2024")},
      {"artist":"Munmro Lemerie","title":"Daugherty-Cummerata","date": new Date("5/30/2024")},
      {"artist":"Tobias Dreus","title":"Rau, Cummerata and Reichel","date": new Date("12/12/2024")},
      {"artist":"Amabel Coniam","title":"Gerlach, Hackett and Jacobi","date": new Date("4/24/2024")},
      {"artist":"Addi Gomer","title":"Kuphal, Macejkovic and Zboncak","date": new Date("5/14/2024")},
      {"artist":"Brandi Marchment","title":"Sipes, Kutch and Stiedemann","date": new Date("6/7/2024")},
      {"artist":"Adolpho Tevelov","title":"Bashirian Group","date": new Date("10/1/2024")},
      {"artist":"Ester Hedau","title":"McKenzie-Schaefer","date": new Date("11/24/2024")},
      {"artist":"Scarlett Lowy","title":"Stoltenberg-Zulauf","date": new Date("1/9/2024")},
      {"artist":"Ardisj Bryers","title":"Lang-Macejkovic","date": new Date("5/29/2024")},
      {"artist":"Adelina Monahan","title":"Torp and Sons","date": new Date("3/6/2024")},
      {"artist":"Orland Gerleit","title":"Brakus-Roberts","date": new Date("4/27/2024")},
      {"artist":"Audy Gherardesci","title":"Frami Group","date": new Date("4/15/2024")},
      {"artist":"Nolly Warhurst","title":"Hirthe-Marks","date": new Date("10/21/2024")},
      {"artist":"Delcina Palphramand","title":"Spinka-Klein","date": new Date("4/9/2024")},
      {"artist":"Adler Ryley","title":"Lemke-Keebler","date": new Date("12/25/2024")},
      {"artist":"Selia Juan","title":"Corkery and Sons","date": new Date("9/30/2024")},
      {"artist":"Juliet Barstock","title":"Denesik-Bailey","date": new Date("8/17/2024")},
      {"artist":"Lindsay McKelloch","title":"McDermott-Hayes","date": new Date("9/21/2024")},
      {"artist":"Aleda Kellog","title":"Rolfson, Fadel and Wuckert","date": new Date("2/20/2024")},
      {"artist":"Benny De Simoni","title":"McDermott Inc","date": new Date("10/8/2024")},
      {"artist":"Annabal Barten","title":"Zboncak, Carroll and Thiel","date": new Date("6/18/2024")},
      {"artist":"Darbee Whitcher","title":"Block, Quitzon and Jones","date": new Date("1/26/2024")},
      {"artist":"Rozamond Collopy","title":"Smith Inc","date": new Date("6/10/2024")},
      {"artist":"Pooh Keeley","title":"Lynch, Corwin and Franecki","date": new Date("12/18/2024")},
      {"artist":"Clarke Fader","title":"Borer Group","date": new Date("2/12/2024")},
      {"artist":"Karen Ryles","title":"Fadel-Price","date": new Date("9/2/2024")},
      {"artist":"Grete Southall","title":"Bernier-McLaughlin","date": new Date("1/2/2024")},
      {"artist":"Georg Firk","title":"Ledner-Miller","date": new Date("4/10/2024")},
      {"artist":"Cart Ida","title":"Gorczany Group","date": new Date("2/12/2024")},
      {"artist":"Lisha Wickstead","title":"Heathcote Group","date": new Date("10/31/2024")},
      {"artist":"Ransom Bolstridge","title":"Rowe, Runte and Gulgowski","date": new Date("5/22/2024")},
      {"artist":"Vanya Compson","title":"Streich Inc","date": new Date("10/27/2024")},
      {"artist":"Schuyler Cuthill","title":"Grimes, Ziemann and Kiehn","date": new Date("1/14/2024")},
      {"artist":"Rhoda Culpan","title":"Morissette Group","date": new Date("6/5/2024")},
      {"artist":"Kial Tesoe","title":"Sanford-Bailey","date": new Date("8/20/2024")},
      {"artist":"Dominik Cubbinelli","title":"Rosenbaum Inc","date": new Date("4/12/2024")},
      {"artist":"Dagmar Lyddiatt","title":"Skiles, Huel and Bode","date": new Date("3/29/2024")},
      {"artist":"Sinclair Deetch","title":"Blick and Sons","date": new Date("11/13/2024")},
      {"artist":"Rowe Brobyn","title":"Balistreri Group","date": new Date("4/14/2024")},
      {"artist":"Lodovico Sigg","title":"Kozey and Sons","date": new Date("7/3/2024")},
      {"artist":"Patton Broadfield","title":"Welch, Bruen and Rodriguez","date": new Date("11/29/2024")},
      {"artist":"Fernanda Prior","title":"Koepp, Barton and Boehm","date": new Date("11/7/2024")},
      {"artist":"Bennett Svanini","title":"Block, Jast and Treutel","date": new Date("2/22/2024")},
      {"artist":"Darin Lazenby","title":"Stehr-Rath","date": new Date("2/26/2024")},
      {"artist":"Courtenay Lepere","title":"Corwin, Huels and Little","date": new Date("12/14/2024")},
      {"artist":"Malissia Skedge","title":"Schumm, Kuvalis and Kulas","date": new Date("3/20/2024")},
      {"artist":"Delcine Huett","title":"Koepp-Reinger","date": new Date("1/2/2024")},
      {"artist":"Cesare Pippin","title":"McKenzie-Kautzer","date": new Date("4/26/2024")},
      {"artist":"Bertie Glowacz","title":"Carter, Bauch and Schneider","date": new Date("9/7/2024")},
      {"artist":"Jacky McInility","title":"Spencer, Hickle and Schneider","date": new Date("12/29/2024")},
      {"artist":"Timi Calam","title":"Jenkins and Sons","date": new Date("2/11/2024")},
      {"artist":"Betteann Base","title":"Fritsch, Paucek and Bogan","date": new Date("4/27/2024")},
      {"artist":"Zechariah Masham","title":"Bauch, Hills and Blick","date": new Date("5/24/2024")},
      {"artist":"Hurlee Najara","title":"Pollich, Mueller and Hirthe","date": new Date("1/15/2024")},
      {"artist":"Igor Connett","title":"Tillman-Stehr","date": new Date("3/10/2024")},
      {"artist":"Broderick Dibbin","title":"Haag-Hammes","date": new Date("4/4/2024")},
      {"artist":"Arlie MacGillreich","title":"Predovic, Goyette and Satterfield","date": new Date("8/26/2024")},
      {"artist":"Aron Jelk","title":"Lockman-Kling","date": new Date("9/21/2024")},
      {"artist":"Dalia Stilliard","title":"Heaney, Stiedemann and Price","date": new Date("9/16/2024")},
      {"artist":"Glenden Chesswas","title":"McCullough, Stokes and Nitzsche","date": new Date("6/5/2024")},
      {"artist":"Betteann Pendall","title":"Tromp-Will","date": new Date("2/3/2024")},
      {"artist":"Hadrian Gingle","title":"Botsford, Littel and Lynch","date": new Date("3/30/2024")},
      {"artist":"Arlen Jovicevic","title":"O'Kon Group","date": new Date("10/27/2024")},
      {"artist":"Tonye Gilleson","title":"Lockman-Brown","date": new Date("2/27/2024")},
      {"artist":"Nerta Draysay","title":"Walsh, Koss and Powlowski","date": new Date("9/30/2024")},
      {"artist":"Dannie Edgar","title":"Upton-Lindgren","date": new Date("9/8/2024")},
      {"artist":"Lane Delgua","title":"Bednar, Wiza and Daugherty","date": new Date("4/12/2024")},
      {"artist":"Tana Creamer","title":"Hickle-Leuschke","date": new Date("11/25/2024")},
      {"artist":"Leanna Grieve","title":"Dickens Inc","date": new Date("8/26/2024")},
      {"artist":"Kelbee Stoad","title":"Klein-Ziemann","date": new Date("2/28/2024")},
      {"artist":"Carola Castana","title":"Jenkins LLC","date": new Date("10/20/2024")},
      {"artist":"Loy Arthey","title":"Muller LLC","date": new Date("12/8/2024")},
      {"artist":"Kimmi Balcon","title":"Quigley LLC","date": new Date("11/24/2024")},
      {"artist":"Emmaline McCosker","title":"Johnson-Murphy","date": new Date("12/11/2024")},
      {"artist":"Ellery Bartelli","title":"Von, Mayer and Fadel","date": new Date("3/1/2024")},
      {"artist":"Annie Buye","title":"Nader Group","date": new Date("11/30/2024")},
      {"artist":"Mavra Tatton","title":"Sauer-Legros","date": new Date("2/6/2024")},
      {"artist":"Rycca Eddison","title":"Ullrich-Grant","date": new Date("9/18/2024")},
      {"artist":"Terri McCromley","title":"Bednar LLC","date": new Date("8/11/2024")},
      {"artist":"Hayward Tonkinson","title":"Walter-Blanda","date": new Date("8/4/2024")},
      {"artist":"Meyer Farnin","title":"Jacobson Inc","date": new Date("6/12/2024")},
      {"artist":"Maurizia Langlands","title":"McDermott-Emard","date": new Date("3/21/2024")},
      {"artist":"Carter Zorzi","title":"Kerluke Inc","date": new Date("3/2/2024")},
      {"artist":"Vania Schechter","title":"Moen Inc","date": new Date("6/21/2024")},
      {"artist":"Juliana Garnsworthy","title":"Ortiz-Johns","date": new Date("3/28/2024")},
      {"artist":"Dinnie Di Bartolommeo","title":"Upton-Harris","date": new Date("4/27/2024")},
      {"artist":"Alfy Monni","title":"Douglas-Lindgren","date": new Date("9/30/2024")},
      {"artist":"Quinton Haycox","title":"Schultz, Keebler and Tillman","date": new Date("5/7/2024")},
      {"artist":"Katherina Harberer","title":"Wiegand, Bode and Reilly","date": new Date("10/5/2024")},
      {"artist":"Karalee Dulin","title":"Davis-Auer","date": new Date("12/16/2024")},
      {"artist":"Veronique Drinkwater","title":"Stark-Harvey","date": new Date("2/5/2024")},
      {"artist":"Roi O'Caine","title":"Osinski Inc","date": new Date("4/30/2024")},
      {"artist":"Nike Kaiser","title":"Monahan, Gislason and Ankunding","date": new Date("10/2/2024")}
    ])
  }
}
